@CoreBanking.API_HostAddress = http://localhost:5280

GET {{CoreBanking.API_HostAddress}}/api/v1/corebanking/customers
Accept: application/json

###

POST {{CoreBanking.API_HostAddress}}/api/v1/corebanking/customers
Content-Type: application/json

{
    "id": "00000000-0000-0000-0000-000000000000",
    "name": "looprevil",
    "address": "tp hcm"
}

###

GET {{CoreBanking.API_HostAddress}}/api/v1/corebanking/accounts
Accept: application/json

###

POST {{CoreBanking.API_HostAddress}}/api/v1/corebanking/accounts
Content-Type: application/json
{
    "customerid": "0198a7da-1280-781b-9fdf-f0618f70da3f"
}

###

PUT {{CoreBanking.API_HostAddress}}/api/v1/corebanking/accounts/0198a27b-3050-736f-9066-694960394b66/deposit
Content-Type: application/json
{
    "amount": 300
}

###

PUT {{CoreBanking.API_HostAddress}}/api/v1/corebanking/accounts/0198a27b-3050-736f-9066-694960394b66/withdraw
Content-Type: application/json
{
    "amount": 150
}

###

PUT {{CoreBanking.API_HostAddress}}/api/v1/corebanking/accounts/0198a27b-3050-736f-9066-694960394b66/transfer
Content-Type: application/json
{
    "amount": 50,
    "destinationAccountNumber": "638907595573658694"
}

###