@CoreBanking.API_HostAddress = http://localhost:5280

GET {{CoreBanking.API_HostAddress}}/api/v1/corebanking/customers
Accept: application/json

###

POST {{CoreBanking.API_HostAddress}}/api/v1/corebanking/customers
Content-Type: application/json

{
    "id": "00000000-0000-0000-0000-000000000000",
    "name": "tulavoi",
    "address": "binh duong"
}

###
