global using Asp.Versioning;
global using CoreBanking.API.Apis;
global using CoreBanking.API.Bootstraping;
global using CoreBanking.API.Models;
global using CoreBanking.API.Services;
global using CoreBanking.Infrastructure.Data;
global using CoreBanking.Infrastructure.Models;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.EntityFrameworkCore;
